#!/bin/bash
# 4 個獨立專案設置完成腳本

echo "====================================="
echo "  Paddle Form OCR - 4 個獨立專案"
echo "====================================="
echo ""

cd "$(dirname "$0")"

echo "專案結構："
echo ""
tree -L 2 -I '__pycache__|*.pyc' .
echo ""

echo "====================================="
echo "  專案 1: 霍夫直線檢測"
echo "====================================="
echo "路徑: 1_Hough_Line_Detection/"
echo "特點: 快速、固定角度（0°/45°/90°/135°）"
echo "依賴: opencv-python, numpy"
echo "用法: python3 preprocess_hough.py --input image.jpg --output result.jpg --verbose"
echo ""

echo "====================================="
echo "  專案 2: Scikit-Learn PCA"
echo "====================================="
echo "路徑: 2_Scikit_Learn_PCA/"
echo "特點: 任意角度、統計方法"
echo "依賴: opencv-python, numpy, scikit-learn"
echo "用法: python3 preprocess_pca.py --input image.jpg --output result.jpg --verbose"
echo ""

echo "====================================="
echo "  專案 3: MobileNetV3 深度學習"
echo "====================================="
echo "路徑: 3_MobileNetV3_DL/"
echo "特點: 最高精度、需要訓練"
echo "依賴: opencv-python, numpy, torch, torchvision, scikit-learn"
echo "訓練: python3 train.py --data-dir ./training_data --epochs 50"
echo "推理: python3 preprocess_dl.py --input image.jpg --output result.jpg --model model.pth"
echo ""

echo "====================================="
echo "  專案 4: OCR 文字識別"
echo "====================================="
echo "路徑: 4_OCR_Recognition/"
echo "特點: 整合方案、完整 OCR 流程"
echo "依賴: paddleocr, opencv-python, numpy"
echo "用法: python3 ocr_parser.py --image test.jpg --output result.json --preprocess --method pca --verbose"
echo ""

echo "====================================="
echo "  快速測試"
echo "====================================="
echo ""
echo "1. 測試霍夫直線檢測："
echo "   cd 1_Hough_Line_Detection && pip install -r requirements.txt"
echo "   python3 preprocess_hough.py --input ../test.jpg --output result.jpg --verbose"
echo ""
echo "2. 測試 PCA："
echo "   cd 2_Scikit_Learn_PCA && pip install -r requirements.txt"
echo "   python3 preprocess_pca.py --input ../test.jpg --output result.jpg --verbose"
echo ""
echo "3. 測試 OCR（不預處理）："
echo "   cd 4_OCR_Recognition && pip install -r requirements.txt"
echo "   python3 ocr_parser.py --image ../test.jpg --output result.json"
echo ""
echo "4. 測試 OCR（使用 PCA 預處理）："
echo "   cd 4_OCR_Recognition"
echo "   python3 ocr_parser.py --image ../test.jpg --output result.json --preprocess --method pca"
echo ""

echo "====================================="
echo "  專案選擇指南"
echo "====================================="
echo ""
echo "• 快速測試/表格文檔     → 專案 1（霍夫直線檢測）"
echo "• 任意角度/純文字       → 專案 2（PCA）"
echo "• 高精度/可訓練         → 專案 3（深度學習）"
echo "• 生產部署/完整流程     → 專案 4（OCR 識別）"
echo ""

echo "✓ 設置完成！"
echo ""
echo "詳細說明請參考各專案的 README.md 檔案"
